#!/usr/bin/env bash
#
# Regenerates INDEX.md for the docs directories that hold one file per item, so
# the index cannot drift from what is actually on disk.
#
#   tools/docs-index.sh          # rewrite the indexes
#   tools/docs-index.sh --check  # fail if any index is out of date
#
# The title of each entry is the first markdown H1 in the file. For work items
# the status is read from a "Status:" line so the index doubles as the queue an
# agent picks from.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

render_index() {
	local dir="$1" heading="$2" blurb="$3" show_status="$4"
	printf '# %s\n\n' "$heading"
	printf '%s\n\n' "$blurb"
	printf '<!-- GENERATED by tools/docs-index.sh -- do not edit by hand. -->\n\n'

	local any=0
	local f title status
	for f in "$dir"/*.md; do
		[ -e "$f" ] || continue
		case "$(basename "$f")" in INDEX.md) continue ;; esac
		any=1
		title="$(grep -m1 '^# ' "$f" | sed 's/^# //')"
		if [ "$show_status" = "yes" ]; then
			status="$(grep -m1 '^Status:' "$f" | sed 's/^Status:[[:space:]]*//')"
			printf -- '- `%s` **%s** — [%s](%s)\n' "${status:-UNKNOWN}" "$title" "$(basename "$f")" "$(basename "$f")"
		else
			printf -- '- [%s](%s)\n' "$title" "$(basename "$f")"
		fi
	done
	[ "$any" -eq 0 ] && printf -- '- _(nothing yet)_\n'
	return 0
}

write_or_check() {
	local dir="$1" heading="$2" blurb="$3" show_status="$4"
	local target="$dir/INDEX.md"
	local tmp
	tmp="$(mktemp)"
	render_index "$dir" "$heading" "$blurb" "$show_status" >"$tmp"

	if [ "$CHECK" -eq 1 ]; then
		if ! diff -q "$target" "$tmp" >/dev/null 2>&1; then
			echo "FAIL  $target is out of date -- run tools/docs-index.sh" >&2
			rm -f "$tmp"
			return 1
		fi
		rm -f "$tmp"
		return 0
	fi

	mv "$tmp" "$target"
	chmod 644 "$target"
	echo "Wrote $target"
}

rc=0

write_or_check docs/decisions \
	"Decisions" \
	"One file per decision, written when the decision is made. Superseding a decision means adding a new file that says so, never editing history." \
	no || rc=1

write_or_check docs/not-fixed-yet \
	"Not fixed yet" \
	"The work queue. Take the topmost OPEN item for the milestone named in docs/status.md." \
	yes || rc=1

write_or_check docs/findings \
	"Findings" \
	"One file per investigation: what was tried, the verbatim error, what it means. Written whether or not the attempt succeeded." \
	no || rc=1

exit "$rc"
