#!/usr/bin/env bash
#
# Generates the runtime persistence unit the release does not ship (NF-006).
#
#   admin/admin-backend/src/main/resources/META-INF/persistence.xml
#
# The entity list is derived from the @Entity annotations in the release source,
# for the reason recorded in
# docs/findings/2026-08-11-schema-generated-from-entities.md: no shipped
# persistence.xml covers the whole model. admin-backend's test unit lists 117
# classes, the union of all shipped units 119, the source 120. Copying the test
# unit would silently drop three entities.
#
# Names that are NOT invented, recovered from the release source:
#   unit name      evotePU            -- @PersistenceContext(unitName = "evotePU")
#   datasource     java:/jdbc/evote   -- @Resource in StatusApplicationService
#                                        and DatabaseSchemaCheckerBean

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUTPUT=admin/admin-backend/src/main/resources/META-INF/persistence.xml
mkdir -p "$(dirname "$OUTPUT")"

{
	cat <<'HEADER'
<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by tools/generate-persistence-xml.sh. Do not edit by hand.

  The release ships no runtime persistence unit at all: all nine persistence.xml
  files in it are under src/test/resources. Without this, deployment fails with

    WFLYWELD0037: Error injecting persistence unit into CDI managed bean.
    Can't find a persistence unit named 'evotePU' in deployment
    admin-backend.war for injection point
    private javax.persistence.EntityManager BaseRepository.em

  The unit name and datasource JNDI name are recovered from the release source,
  not chosen. The entity list is every @Entity in main source, which is the only
  complete set available.

  Declared GENERATED in manifest/changes.tsv. See docs/not-fixed-yet/NF-006.
-->
<persistence version="2.1"
             xmlns="http://xmlns.jcp.org/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence
             http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">
    <persistence-unit name="evotePU" transaction-type="JTA">
        <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
        <jta-data-source>java:/jdbc/evote</jta-data-source>
HEADER

	grep -rl "^@Entity" admin --include=*.java \
		| grep "/src/main/" \
		| while IFS= read -r file; do
			package="$(sed -n 's/^package \(.*\);$/\1/p' "$file" | head -1)"
			class="$(basename "$file" .java)"
			printf '%s.%s\n' "$package" "$class"
		done \
		| sort -u \
		| sed 's|^|        <class>|; s|$|</class>|'

	# Tuning copied from the release's own test unit, so runtime behaviour
	# matches what the project configured for itself.
	cat <<'FOOTER'
        <exclude-unlisted-classes>true</exclude-unlisted-classes>
        <properties>
            <property name="hibernate.dialect" value="org.hibernate.dialect.PostgreSQL9Dialect"/>
            <property name="hibernate.show_sql" value="false"/>
            <property name="hibernate.jdbc.batch_size" value="1000"/>
            <property name="hibernate.order_inserts" value="true"/>
            <property name="hibernate.order_updates" value="true"/>
            <property name="hibernate.cache.use_second_level_cache" value="false"/>
        </properties>
    </persistence-unit>
</persistence>
FOOTER
} >"$OUTPUT"

echo "Wrote $OUTPUT with $(grep -c '<class>' "$OUTPUT") entity classes"
