#!/usr/bin/env bash
#
# Generates the i18n resource bundles the release does not ship (NF-022).
#
#   admin/admin-common/src/main/resources-unfiltered/no/valg/eva/admin/common/Messages_nb_NO.properties
#   admin/admin-common/src/main/resources-unfiltered/no/valg/eva/admin/common/Messages_nn_NO.properties
#
# Without the bundle every JSF page dies before rendering:
#
#   MissingResourceException: Can't find bundle for base name
#   no.valg.eva.admin.common.Messages, locale nb_NO
#
# The keys are not invented. Every message key in EVA Admin starts with '@' and
# they are all referenced from the XHTML pages and the Java source, so the set is
# recoverable by reading the code that uses them. The VALUES are not recoverable:
# the real Norwegian text was in the withheld bundle and, per election event, in
# the database (TranslationProvider consults LocaleText first, this bundle
# second).
#
# So each value here is a placeholder derived from its own key. That makes the
# application render and navigable, and makes it obvious on screen which label is
# still a placeholder -- which is what the later screenshot comparison needs.
# Nothing here should be mistaken for EVA Admin's real wording.
#
# The format is "@key<space>value", copied from the bundles the release ships as
# test fixtures.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT_DIR=admin/admin-common/src/main/resources-unfiltered/no/valg/eva/admin/common
KEYS=tools/schema-export/target/message-keys.txt
mkdir -p "$OUT_DIR" "$(dirname "$KEYS")"

{
	# From the pages
	grep -rhoE '@[a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z0-9_]+)+' \
		admin/admin-frontend/src/main/webapp --include=*.xhtml 2>/dev/null || true
	# From the code, main source only
	grep -rhoE '"@[a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z0-9_]+)+"' \
		admin --include=*.java 2>/dev/null | tr -d '"' || true
} | sed 's/[.,;:]*$//' | sort -u | grep -vE '^@$' >"$KEYS"

echo "Message keys recovered from source: $(wc -l <"$KEYS")"

# Any keys the release did ship, as test fixtures. Real wording beats a
# placeholder, so these win.
FIXTURES=$(find admin -path "*test/resources-unfiltered*" -name "Messages_nb_NO.properties" 2>/dev/null | head -5)

write_bundle() {
	local locale="$1"
	local out
	if [ -z "$locale" ]; then
		out="$OUT_DIR/Messages.properties"
	else
		out="$OUT_DIR/Messages_$locale.properties"
	fi

	{
		printf '# GENERATED by tools/generate-message-bundle.sh. Do not edit by hand.\n'
		printf '#\n'
		printf '# Keys recovered from the XHTML pages and Java source of the release.\n'
		printf '# Values are PLACEHOLDERS derived from the keys: the real Norwegian text\n'
		printf '# was never published, and per election event lives in the database.\n'
		printf '# Locale: %s. See docs/not-fixed-yet/NF-022.\n' "${locale:-default fallback}"
		printf '#\n'

		while IFS= read -r key; do
			# Humanise the last two segments: @rbac.operator.lastName -> "Operator last name"
			label="$(printf '%s' "$key" \
				| sed 's/^@//' \
				| awk -F. '{ if (NF>1) print $(NF-1)"."$NF; else print $NF }' \
				| sed 's/\./ /g' \
				| sed 's/\([a-z0-9]\)\([A-Z]\)/\1 \2/g' \
				| sed 's/_/ /g')"
			# Capitalise, and mark the locale so nb and nn are distinguishable on screen
			label="$(printf '%s' "$label" | sed 's/^./\U&/')"

			# Some keys are not display text: they are FORMAT PATTERNS that the
			# code feeds to a formatter. A humanised placeholder there is not
			# merely ugly, it throws:
			#   IllegalArgumentException: Illegal pattern component: t
			#   at AbstractDateOrTimeConverter.getAsString
			# because Joda parses "Date date pattern" as pattern letters.
			#
			# The first two values are the release's own fallbacks, taken from
			# the converters' constructors:
			#   DateConverter      super("@common.date.date_pattern", "yyyy-MM-dd")
			#   DateTimeConverter  super("@common.date.date_time_pattern", "yyyy-MM-dd HH:mm")
			# The rest follow the same style; no fallback is given for them in
			# the source.
			case "$key" in
			'@common.date.date_pattern' | '@common.date.date_display_pattern' | '@common.date.date_format')
				label='yyyy-MM-dd' ;;
			'@common.date.date_time_pattern')
				label='yyyy-MM-dd HH:mm' ;;
			'@common.date.time_pattern' | '@common.date.time_display_pattern')
				label='HH:mm' ;;
			'@common.date.date_mask')
				label='9999-99-99' ;;
			'@common.date.time_mask')
				label='99:99' ;;
			esac

			printf '%s %s\n' "$key" "$label"
		done <"$KEYS"
	} >"$out"

	echo "Wrote $out ($(grep -c '^@' "$out") keys)"
}

# The default bundle, with no locale suffix, is the fallback ResourceBundle uses
# for any locale we do not ship. Without it a client whose locale resolves to,
# say, en_US gets
#   MissingResourceException: Can't find bundle for base name
#   no.valg.eva.admin.common.Messages, locale en_US
# and the page fails, even though nb_NO exists.
write_bundle ""
write_bundle nb_NO
write_bundle nn_NO

# Overlay the genuine strings the release did ship in its test fixtures.
if [ -n "$FIXTURES" ]; then
	echo "Real strings available from release test fixtures:"
	for f in $FIXTURES; do
		printf '  %s (%s lines)\n' "$f" "$(grep -c '^@' "$f" || true)"
	done
	echo "  (not merged automatically: they are test data, and their encoding is not UTF-8)"
fi
