#!/usr/bin/env bash
#
# Generates PageAccess.properties, the page-level authorisation map (NF-023).
#
# DISABLES A SECURITY FEATURE. Every page is mapped to "*", meaning open to any
# authenticated operator. Read docs/decisions/D012 before relying on anything
# this application shows about authorisation.
#
# The release ships no PageAccess.properties, and PageAccess.load() reads it from
# the classpath root, so without it every secure page dies with a
# NullPointerException on an absent InputStream.
#
# Unlike the message keys, this map is NOT recoverable. It pairs 207 secure pages
# with 156 constants of the Accesses enum, and nothing in the published source
# records which page needs which: no page references an access name, and the
# pairing existed only in this file.
#
# So the honest options were an invented mapping or an open one. An invented
# mapping would look like authorisation while enforcing rules nobody chose, which
# is worse than none: it would be indistinguishable from the real thing in a
# screenshot. Open, loudly documented, is the lesser evil.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

WEBAPP=admin/admin-frontend/src/main/webapp
OUT=admin/admin-frontend/src/main/resources/PageAccess.properties

{
	cat <<'HEADER'
# GENERATED by tools/generate-page-access.sh. Do not edit by hand.
#
# PAGE-LEVEL AUTHORISATION IS DISABLED. Every page below is mapped to "*", which
# PageAccess treats as open to any authenticated operator.
#
# The release does not ship this file and its contents cannot be recovered: it
# paired these pages with constants of the Accesses enum, and no page, class or
# config in the published source records which page required which access.
#
# What this means when reading the running application:
#   - Any logged-in operator reaches every page, regardless of role.
#   - Screens that should be barred by role are not evidence of anything.
#   - No screenshot of this system demonstrates EVA Admin's real authorisation.
#
# Restoring real values needs the mapping from a source outside this repository.
# See docs/decisions/D012 and docs/not-fixed-yet/NF-023.
HEADER
	printf '\n'

	find "$WEBAPP/secure" -name "*.xhtml" \
		| sed "s|^$WEBAPP||" \
		| sort \
		| while IFS= read -r page; do
			printf '%s=*\n' "$page"
		done
} >"$OUT"

echo "Wrote $OUT ($(grep -c '=\*$' "$OUT") pages, all open)"
