#!/usr/bin/env bash
#
# Regenerates manifest/originals.sha from the baseline commit in manifest/BASELINE.
#
# The output is committed. That is deliberate: if someone moves the baseline, the
# regenerated file changes and the move is visible in review rather than silent.
#
# Run this only when the baseline itself changes (i.e. essentially never).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# shellcheck disable=SC1091
source manifest/BASELINE

OUT=manifest/originals.sha
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
	printf '# GENERATED by tools/manifest-generate.sh -- do not edit by hand.\n'
	printf '# Format: <blob-sha><TAB><path>\n'
	printf '# Baseline: %s\n' "$BASELINE_COMMIT"
	printf '# Override: %s taken from %s\n' "$README_BASELINE_PATH" "$README_BASELINE_COMMIT"
} >"$TMP"

# core.quotePath=false keeps Norwegian characters in paths readable (the release
# has files such as .../oppgjørsskjema/OppgjørsskjemaDomainService.java).
git -c core.quotePath=false ls-tree -r "$BASELINE_COMMIT" \
	| awk -F'\t' '{ split($1, m, " "); print m[3] "\t" $2 }' \
	| sort -t"$(printf '\t')" -k2 \
	>>"$TMP"

# Apply the readme.md override.
README_BLOB="$(git rev-parse "${README_BASELINE_COMMIT}:${README_BASELINE_PATH}")"
awk -F'\t' -v path="$README_BASELINE_PATH" -v blob="$README_BLOB" \
	'BEGIN { OFS="\t" } $2 == path { $1 = blob } { print }' "$TMP" >"$OUT"

echo "Wrote $OUT ($(grep -cv '^#' "$OUT") original files)"
