package no.valg.eva.admin.frontend.configuration;

/**
 * Created by dba on 28/12/15.
 */
public enum ConfigurationView {

	ADVANCE_POLLING_PLACES,
	ELECTRONIC_MARKOFFS,
	ELECTION_DAY_POLLING_PLACES,
	ORDINARY_POLLING_PLACES,
	PARENT_POLLING_DISTRICT,
	POLLING_STATION,
	COUNT,
	ELECTION_CARD,
	BOROUGHS_ELECTION_CARD,
	LANGUAGE,
	TECHNICAL_POLLING_DISTRICT,
	LIST_PROPOSAL,
	BOROUGHS_LIST_PROPOSAL,
	FYLKESVALGSTYRE,
	VALGSTYRE,
	STEMMESTYRE,
	BOROUGHS_STEMMESTYRE,
	OPPTELLINGSVALGSTYRE,
	SCANNING
}
