package no.valg.eva.tools;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import no.valg.eva.admin.common.rbac.Accesses;

/**
 * Emits SQL for the {@code access} and {@code role_access} tables, straight from
 * the release's own {@code Accesses} enum.
 *
 * The enum builds its paths hierarchically ({@code konfig}, then
 * {@code konfig.valghendelse}, then {@code konfig.valghendelse.opprett}), so
 * enumerating it is exact where re-deriving the paths by parsing the source
 * would be a guess.
 *
 * Every access is granted to the seeded role. That is a demo decision, not a
 * reconstruction of any real role: which accesses a real Valghendelsesadministrator
 * holds is not published. See NF-026.
 */
public final class AccessDump {

	private AccessDump() {
	}

	public static void main(String[] args) {
		long rolePk = args.length > 0 ? Long.parseLong(args[0]) : 1L;

		// Not every constant is a row. Accesses has two kinds: standard ones that
		// wrap a single Access, and aggregated ones that stand for a union of
		// others and are evaluated in code. getAccess() throws
		// UnsupportedOperationException for the aggregated kind, and those
		// correctly have no row in the access table.
		List<String> paths = new ArrayList<>();
		int aggregated = 0;
		for (Accesses access : Accesses.values()) {
			try {
				paths.add(access.getAccess().getPath());
			} catch (UnsupportedOperationException e) {
				aggregated++;
			}
		}
		Collections.sort(paths);
		System.err.println("Aggregated accesses skipped (no table row): " + aggregated);

		PrintWriter out = new PrintWriter(System.out);
		out.println("-- GENERATED by tools/schema-export AccessDump. Do not edit by hand.");
		out.println("--");
		out.println("-- One row per constant of no.valg.eva.admin.common.rbac.Accesses, taken from");
		out.println("-- the enum itself rather than re-derived, plus a role_access row granting");
		out.println("-- every one of them to the seeded role.");
		out.println("--");
		out.println("-- GRANTING EVERYTHING IS A DEMO DECISION. Which accesses a real");
		out.println("-- Valghendelsesadministrator holds is not published, so this is not a");
		out.println("-- reconstruction of any real role. See NF-026.");
		out.println();
		out.println("DELETE FROM role_access;");
		out.println("DELETE FROM access;");
		out.println();

		long pk = 0;
		for (String path : paths) {
			pk++;
			String name = "@access." + path;
			if (name.length() > 50) {
				name = name.substring(0, 50);
			}
			out.printf(
					"INSERT INTO access (access_pk, audit_oplock, access_name, access_path) VALUES (%d, 0, %s, %s);%n",
					pk, quote(name), quote(path));
		}

		out.println();
		for (long i = 1; i <= pk; i++) {
			out.printf(
					"INSERT INTO role_access (role_access_pk, role_pk, access_pk, audit_oplock) VALUES (%d, %d, %d, 0);%n",
					i, rolePk, i);
		}

		out.println();
		out.printf("SELECT setval('access_access_pk_seq', %d, true);%n", pk);
		out.flush();

		System.err.println("Emitted " + pk + " accesses, all granted to role_pk=" + rolePk);
	}

	private static String quote(String value) {
		return "'" + value.replace("'", "''") + "'";
	}
}
